### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#70]
**Milestone**
Play a 2 player game online to the end.

**Goals (roughly in order of completion)**
- [x] Deploy Go server to EC2 (watch out for WebSockets!) and connect to the UI
- [x] Make the UI display *all* relevant game data (like tax chart and power points)
  - Handle fleets
  - Display armies and fleets (SVG wrangling)
  - Display dots for each province's owner
  - Display factories
- [x] Handle passing game log/moves between server and clients
- [x] Make Go server handle multiple games (using Vue router)
- [x] Handle invalid moves gracefully (whether malicious or not)
- [x] Handle more than 2 players
- [x] Connect a database to save users
- [ ] Handle user authentication
- [ ] Improve/finalize the UI (VueJS)
